org.jfree.chart.axis.junit.NumberAxisTests::testXYAutoRange2$catena_0
org.jfree.chart.axis.junit.LogAxisTests::testXYAutoRange2$catena_1
org.jfree.chart.junit.XYAreaChartTests::testDrawWithNullInfo
org.jfree.chart.junit.TimeSeriesChartTests::testReplaceDataset$catena_2
org.jfree.chart.junit.XYStepAreaChartTests::testDrawWithNullInfo
org.jfree.chart.junit.ScatterPlotTests::testSetSeriesToolTipGenerator
org.jfree.chart.axis.junit.NumberAxisTests::testXYAutoRange1$catena_0
org.jfree.chart.axis.junit.NumberAxisTests::testXYAutoRange1$catena_1
org.jfree.chart.axis.junit.LogAxisTests::testXYAutoRange1$catena_0
org.jfree.chart.junit.ScatterPlotTests::testReplaceDataset$catena_0
org.jfree.chart.junit.TimeSeriesChartTests::testDrawWithNullInfo
org.jfree.chart.junit.XYAreaChartTests::testSetSeriesToolTipGenerator
org.jfree.chart.junit.XYStepAreaChartTests::testSetSeriesToolTipGenerator
org.jfree.chart.axis.junit.LogAxisTests::testXYAutoRange2$catena_0
org.jfree.chart.junit.XYStepChartTests::testReplaceDataset$catena_1
org.jfree.chart.junit.XYStepAreaChartTests::testReplaceDataset$catena_1
org.jfree.chart.junit.ScatterPlotTests::testReplaceDataset$catena_1
org.jfree.chart.plot.junit.XYPlotTests::testDrawRangeGridlines
org.jfree.chart.junit.XYStepChartTests::testDrawWithNullInfo
org.jfree.chart.axis.junit.NumberAxisTests::testXYAutoRange2$catena_1
org.jfree.chart.junit.XYAreaChartTests::testReplaceDataset$catena_2
org.jfree.chart.junit.TimeSeriesChartTests::testReplaceDataset$catena_1
org.jfree.chart.axis.junit.ValueAxisTests::testAxisMargins$catena_0
org.jfree.chart.junit.ScatterPlotTests::testDrawWithNullInfo
org.jfree.chart.junit.TimeSeriesChartTests::testReplaceDataset$catena_0
org.jfree.chart.junit.XYStepAreaChartTests::testReplaceDataset$catena_0
org.jfree.chart.junit.XYStepChartTests::testReplaceDataset$catena_0
org.jfree.chart.axis.junit.LogAxisTests::testXYAutoRange1$catena_1
org.jfree.chart.axis.junit.ValueAxisTests::testAxisMargins$catena_1
org.jfree.chart.junit.ScatterPlotTests::testReplaceDataset$catena_2
org.jfree.chart.junit.XYAreaChartTests::testReplaceDataset$catena_1
org.jfree.chart.junit.XYStepChartTests::testReplaceDataset$catena_2
org.jfree.chart.junit.XYStepChartTests::testSetSeriesToolTipGenerator
org.jfree.chart.junit.XYStepAreaChartTests::testReplaceDataset$catena_2
org.jfree.chart.junit.TimeSeriesChartTests::testSetSeriesToolTipGenerator
org.jfree.chart.junit.JFreeChartTests::testSerialization4
org.jfree.chart.junit.XYAreaChartTests::testReplaceDataset$catena_0
