org.apache.commons.math.optimization.linear.SimplexSolverTest::testSingleVariableAndConstraint$catena_1
org.apache.commons.math.optimization.linear.SimplexSolverTest::testSingleVariableAndConstraint$catena_0
