com.google.javascript.jscomp.TypedScopeCreatorTest::testGlobalQualifiedNameInLocalScope$catena_1
com.google.javascript.jscomp.TypedScopeCreatorTest::testGlobalQualifiedNameInLocalScope$catena_2
com.google.javascript.jscomp.TypeCheckTest::testQualifiedNameInference5
