com.google.javascript.jscomp.TypeCheckTest::testImplementsLoop
com.google.javascript.jscomp.TypeCheckTest::testConversionFromInterfaceToRecursiveConstructor
com.google.javascript.jscomp.TypeCheckTest::testImplementsExtendsLoop
