com.google.javascript.jscomp.CollapsePropertiesTest::testCrashInCommaOperator
com.google.javascript.jscomp.CollapsePropertiesTest::testCrashInNestedAssign
com.google.javascript.jscomp.CollapsePropertiesTest::testTwinReferenceCancelsChildCollapsing
