org.mockito.internal.util.TimerTest::should_throw_friendly_reminder_exception_when_duration_is_negative$catena_0
org.mockito.verification.NegativeDurationTest::should_throw_exception_when_duration_is_negative_for_timeout_method$catena_0
org.mockito.verification.NegativeDurationTest::should_throw_exception_when_duration_is_negative_for_after_method$catena_0
