org.mockitousage.constructor.CreatingMocksWithConstructorTest::can_mock_abstract_classes
org.mockitousage.annotation.SpyAnnotationTest::should_report_when_constructor_is_explosive$catena_0
org.mockitousage.constructor.CreatingMocksWithConstructorTest::exception_message_when_constructor_not_found$catena_0
org.mockitousage.constructor.CreatingMocksWithConstructorTest::can_mock_inner_classes
org.mockitousage.annotation.SpyAnnotationTest::should_spy_inner_class$catena_1
org.mockitousage.constructor.CreatingMocksWithConstructorTest::can_spy_abstract_classes
org.mockitousage.constructor.CreatingMocksWithConstructorTest::mocking_inner_classes_with_wrong_outer_instance$catena_0
org.mockitousage.constructor.CreatingMocksWithConstructorTest::can_create_mock_with_constructor
